#!/bin/bash

#DATE: 01.06.2016
#Author: Alexander Orlowski
#Description:
#This Plugin will output all Clients of a Subnet which are current online
#It will also displayed all Clients that wore online in a specific time period
#PerformanceData will be stored for Graphite/Grafana use.

#Vars
PERFDAT=""
PERFDAT2=""
NIGHTSTART=1300
NIGHTEND=1500
SUBNET=""
SUBNETNAME=""
WARNING=50
CRITICAL=100
EXCLUDE=
EXITCODE=""

#For Clients who cant get resolved over DNS
NO_DNS="3(NXDOMAIN)"

#Get Time in Format HHMM e.g  1500 = 15:00 PM
TIME_WATCH=$(date "+%H%M")

#Function for Printing Helptext
function print_help {
echo
echo "check_client_watch usage:"
echo
echo "./check_client_watch -sn IP-SUBNET -n SUBNETNAME -s NIGHTSTART -e NIGHTEND -c VALUE -w VALUE -x"
echo
echo "~~~DESCRIPTION~~~"
echo
echo "-sn or --subnet		: range of subnet to ping in CIDR-Format e.g. 192.168.1.0/24 *REQUIRED*"
echo "-n or --name		: name of subnet e.g. CLIENTS or WLAN *REQUIRED*"
echo "-s or --start		: time when nightwatch will start DEFAULT=0000 (00:00 AM) *OPTIONAL*"
echo "-e or --end		: time when nightwatch will end DEFAULT=0300 (03:00 AM) *OPTIONAL*"
echo "-w or --warning		: warning value for clients online at night DEFAULT=50"
echo "-c or --critical	: critical value for clients online at night DEFAULT=100"
echo "-x or --exclude		: hostnames or IPs which will be excluded from nightwatch by excludefile /tmp/exclude_hosts_$SUBNETNAME "
echo "-h or --help      	: will print this Help"
echo
echo "EXAMPLE:"
echo "./check_client_watch -sn 192.168.1.0/24 -n Clients -s 0000 -e 0300 -w 20 -c 50 -x"
echo "./check_client_watch --subnet 192.168.1.0/24 --name Clients --start 0000 --end 0300 --warning 20 --critical 50 --exclude"
echo
exit 3
}

#check script parameters

if [ -z $1 ]; then
print_help
fi


for ((i=1;i<=$#;i++));

do
 if [ ${!i} = "--subnet" ] || [ ${!i} = "-sn" ]
 	then ((i++))
		SUBNET=${!i};
 elif [ ${!i} = "--name" ] || [ ${!i} =  "-n" ]
	then ((i++))
		SUBNETNAME=${!i};
 elif [ ${!i} = "--start" ] || [ ${!i} = "-s" ]
	then ((i++))
		NIGHTSTART=${!i};
 elif [ ${!i} = "--end" ] || [ ${!i} = "-e" ]
	then ((i++))
		NIGHTEND=${!i};
 elif [ ${!i} = "--help" ] || [ ${!i} = "-h" ]
	then ((i++))
		print_help
 elif [ ${!i} = "--warning" ] || [ ${!i} = "-w" ]
	then ((i++))
		WARNING=${!i};
 elif [ ${!i} = "--critical" ] || [ ${!i} = "-c" ]
	then ((i++))
		CRITICAL=${!i};
 elif [ ${!i} = "--exclude" ] || [ ${!i} = "-x" ]
	then ((i++))
		EXCLUDE="true";

fi
done



#Check if the file /tmp/nighthosts_$SUBNETNAME.txt exists
if [ ! -f /tmp/nighthosts_$SUBNETNAME.txt ]; then
touch /tmp/nighthosts_$SUBNETNAME.txt
fi

#Check if the file /tmp/exclude_hosts_$SUBNETNAME.txt exists
if [ ! -f /tmp/exclude_hosts_$SUBNETNAME.txt ]; then
touch /tmp/exclude_hosts_$SUBNETNAME.txt
fi


#Ping Subnet in $1 and output all Online Client on /tmp/check_fing_$SUBNETNAME.txt
fping -a -g $SUBNET -q -r 1 > /tmp/check_client_watch_$SUBNETNAME.txt

#Count Lines of /tmp/check_client_watch_$SUBNETNAME.txt
OnlineClientsCount=$(cat /tmp/check_client_watch_$SUBNETNAME.txt | wc -l )
PERFDAT="Online_Clients=$OnlineClientsCount;"


# Check if its Night 
# This Check will be active form NIGHTSTART to NIGHTEND default is 00:00 - 03:00 AM (0000 <= 0300)
# and will output it in /tmp/nighthosts_$SUBNETNAME.txt
if [ $TIME_WATCH -le $NIGHTEND ] && [ $TIME_WATCH -ge $NIGHTSTART ]; then
echo > /tmp/nighthosts_$SUBNETNAME.txt
fi

#Get all Clients form from fping
cat /tmp/check_client_watch_$SUBNETNAME.txt | while read LINE
 do
  line_hostename=""
  line_hostname=$(host $LINE | awk '{print $5}')

 if [ $TIME_WATCH -le $NIGHTEND ] && [ $TIME_WATCH -ge $NIGHTSTART ]; then

 if [ $line_hostname =  $NO_DNS ]; then

  #echo $LINE
  echo $LINE >>  /tmp/nighthosts_$SUBNETNAME.txt
 else

   #echo $line_hostname
   echo $line_hostname >> /tmp/nighthosts_$SUBNETNAME.txt

fi
fi
done

if [ ! -z $EXCLUDE ]; then
#
ARRAYITEMS=$(cat  /tmp/nighthosts_$SUBNETNAME.txt |tr "\n" " ")
EXCLUDEITEMS=$(cat  /tmp/exclude_hosts_$SUBNETNAME.txt |tr "\n" " ")
#
for del in ${EXCLUDEITEMS[@]};
 do
	ARRAYITEMS=(${ARRAYITEMS[@]/$del})
 done
 
 #Clear the nighthosts_$SUBNETNAME.txt
 echo > /tmp/nighthosts_$SUBNETNAME.txt
 
for nighthosts in ${ARRAYITEMS[@]};
 do
	echo $nighthosts >> /tmp/nighthosts_$SUBNETNAME.txt
done
fi 
#Count Clients Online at night minus 1
#Because one line in /tmp/nighthosts_$SUBNETNAME.txt is empty
NightClientsCount=$(expr $(cat /tmp/nighthosts_$SUBNETNAME.txt | wc -l) - 1)
ExcludeClientsCount=$(cat /tmp/exclude_hosts_$SUBNETNAME.txt | wc -l)
OnlineClientsExcludeCount=$(expr $OnlineClientsCount - $ExcludeClientsCount)

if [ "$OnlineClientsExcludeCount" -lt "0" ]; then
 OnlineClientsExcludeCount=0
fi


PERFDAT2="Online_Clients_with_Excludes=$OnlineClientsExcludeCount"
#Outputfunction

function plugin_output {
echo -----------------------------------------
echo ---------CLIENTS ONLINE AT NIGHT---------
echo -----------------------------------------
cat /tmp/nighthosts_$SUBNETNAME.txt
echo
echo -----------------------------------------
echo $NightClientsCount "clients online at night";
echo -----------------------------------------
echo -------------CLIENTS ONLINE--------------
echo -----------------------------------------
echo $OnlineClientsCount  "clients are online | $PERFDAT";
echo $OnlineClientsExcludeCount "clients are online with excludes | $PERFDAT2";
exit $EXITCODE
}

#OK;WARNING;CRITICAL

if [ -n $WARNING ] && [ -n $CRITICAL ]; then

if [ $NightClientsCount -ge $WARNING ]; then

if [ $NightClientsCount -ge $CRITICAL ]; then
	echo "CRITICAL: "  $NightClientsCount " Clients online this night" 
	EXITCODE=2
	plugin_output
	
fi
	echo "WARNING: "  $NightClientsCount " Clients online this night"
	EXITCODE=1
	plugin_output
fi

	echo "OK: "  $NightClientsCount  " Clients online this night"
	EXITCODE=0
	plugin_output
fi

